### PR TITLE
Add GCC ML training videos

### PR DESCRIPTION
**Pull request by anuprulez**
This PR adds training videos of machine learning (Introduction to ML, Classification and Regression in ML) for GCC 2021 and the relevant information to the `yaml` file. FAQs are empty for now but soon they will have useful questions and their answers.

Also, here is the link to the speaker introduction (I am not sure where to add this link): 
https://www.youtube.com/watch?v=_coXYYmdTCg

Thanks!

### CODE REVIEW

**Comment by hexylena** [comment]
Hi @anuprulez. Would you be OK with us moving those under the Galaxyproject account? 

We'd like to do that to have access to all of the statistics for the conference, and we need to ensure captioning is done as well.

**Comment by hexylena** [comment]
Otherwise this is fantastic! Thanks for getting those in so early!!

**Comment by anuprulez** [comment]
> Hi @anuprulez. Would you be OK with us moving those under the Galaxyproject account?
> 
> We'd like to do that to have access to all of the statistics for the conference, and we need to ensure captioning is done as well.

Yes, sure. Please go ahead. @hexylena

**Review by hexylena — APPROVED** [review]

**Comment by hexylena** [comment]
Hey @anuprulez ok, everything is online now :)

Here are the documents for the subtitles from your videos, can you please go through them and make the first pass of corrections? 

- [intro](https://docs.google.com/document/d/1alo8imCIRow5gRgE_H3hAiykNff12P4DRPXKjMjClW0/edit)
- [classification](https://docs.google.com/document/d/18aUWy_Of7K14Ju_icOuFerXLusd8dVyKaFfdRr6tKNc/edit)
- [regression](https://docs.google.com/document/d/1wYb22oMmjRiV7_ml_KPLNrLO_hTFXEkNJ2lcPHSD1nE/edit)

after that we'll share them with the GTN community for anyone else who might be willing to double check them

**Comment by anuprulez** [comment]
Hi Helena,

I have corrected the captions/subtitles for all three videos in the same
shared files. The subtitles for the first video (Introduction to ML) is
updated already. Thanks!


Best,
Anup

**Comment by hexylena** [comment]
Amazing, thank you so much!

I'll get the rest posted asap.

**Pull request merged**
